server:
  port: ${SERVER_PORT:8002}

spring:
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/temp
    username: thangavel
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: false
    generate-dll: true
    hibernate:
      ddl-auto: update

# Health check endpoints
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"